// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/swaggersocket/example/autogen/models"
)

// GetPetsReader is a Reader for the GetPets structure.
type GetPetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPetsOK creates a GetPetsOK with default headers values
func NewGetPetsOK() *GetPetsOK {
	return &GetPetsOK{}
}

/* GetPetsOK describes a response with status code 200, with default header values.

A list of pets.
*/
type GetPetsOK struct {
	Payload []*models.Pet
}

func (o *GetPetsOK) Error() string {
	return fmt.Sprintf("[GET /pets][%d] getPetsOK  %+v", 200, o.Payload)
}
func (o *GetPetsOK) GetPayload() []*models.Pet {
	return o.Payload
}

func (o *GetPetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
