// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPetsParams creates a new GetPetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPetsParams() *GetPetsParams {
	return &GetPetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPetsParamsWithTimeout creates a new GetPetsParams object
// with the ability to set a timeout on a request.
func NewGetPetsParamsWithTimeout(timeout time.Duration) *GetPetsParams {
	return &GetPetsParams{
		timeout: timeout,
	}
}

// NewGetPetsParamsWithContext creates a new GetPetsParams object
// with the ability to set a context for a request.
func NewGetPetsParamsWithContext(ctx context.Context) *GetPetsParams {
	return &GetPetsParams{
		Context: ctx,
	}
}

// NewGetPetsParamsWithHTTPClient creates a new GetPetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPetsParamsWithHTTPClient(client *http.Client) *GetPetsParams {
	return &GetPetsParams{
		HTTPClient: client,
	}
}

/* GetPetsParams contains all the parameters to send to the API endpoint
   for the get pets operation.

   Typically these are written to a http.Request.
*/
type GetPetsParams struct {

	/* XCorrelationID.

	   Correlation id if swagger over websocket
	*/
	XCorrelationID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetsParams) WithDefaults() *GetPetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pets params
func (o *GetPetsParams) WithTimeout(timeout time.Duration) *GetPetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pets params
func (o *GetPetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pets params
func (o *GetPetsParams) WithContext(ctx context.Context) *GetPetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pets params
func (o *GetPetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pets params
func (o *GetPetsParams) WithHTTPClient(client *http.Client) *GetPetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pets params
func (o *GetPetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCorrelationID adds the xCorrelationID to the get pets params
func (o *GetPetsParams) WithXCorrelationID(xCorrelationID *string) *GetPetsParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the get pets params
func (o *GetPetsParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XCorrelationID != nil {

		// header param X-Correlation-Id
		if err := r.SetHeaderParam("X-Correlation-Id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
