// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPetsHandlerFunc turns a function with the right signature into a get pets handler
type GetPetsHandlerFunc func(GetPetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPetsHandlerFunc) Handle(params GetPetsParams) middleware.Responder {
	return fn(params)
}

// GetPetsHandler interface for that can handle valid get pets params
type GetPetsHandler interface {
	Handle(GetPetsParams) middleware.Responder
}

// NewGetPets creates a new http.Handler for the get pets operation
func NewGetPets(ctx *middleware.Context, handler GetPetsHandler) *GetPets {
	return &GetPets{Context: ctx, Handler: handler}
}

/* GetPets swagger:route GET /pets getPets

Returns all pets from the system that the user has access to

*/
type GetPets struct {
	Context *middleware.Context
	Handler GetPetsHandler
}

func (o *GetPets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPetsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
