// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/go-openapi/swaggersocket/example/autogen/models"
)

// GetPetsOKCode is the HTTP code returned for type GetPetsOK
const GetPetsOKCode int = 200

/*GetPetsOK A list of pets.

swagger:response getPetsOK
*/
type GetPetsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pet `json:"body,omitempty"`
}

// NewGetPetsOK creates GetPetsOK with default headers values
func NewGetPetsOK() *GetPetsOK {

	return &GetPetsOK{}
}

// WithPayload adds the payload to the get pets o k response
func (o *GetPetsOK) WithPayload(payload []*models.Pet) *GetPetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pets o k response
func (o *GetPetsOK) SetPayload(payload []*models.Pet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Pet, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
