// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Petstore
//
//  A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: petstore.swagger.io
//  BasePath: /api
//  Version: 1.0.0
//  License: MIT
//  Contact: Swagger API Team
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
